[Workspace]
Home=..\
AppHTMLPath=.
AppSrcPath=AppSrc
DataPath=Data
DDSrcPath=DDSrc
BitmapPath=.
IdeSrcPath=IdeSrc
HelpPath=.
ProgramPath=Programs
FileList=Data\Filelist.cfg
Description=YamlObjectTests.dev
